[package]
name = 'acridotheres_core'
version = '0.2.1'
edition = '2021'

[lib]
name = 'corelib'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
crc32fast = "1.4.2"
