[package]
name = 'acridotheres_core'
version = '0.3.0'
edition = '2021'

[lib]
name = 'corelib'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
crc32fast = "1.4.2"
dh = "0.4.0"
libaes = "0.7.0"
murmur3 = "0.5.2"
sha2 = "0.10.8"
