[package]
name = 'acridotheres'
version = '0.3.0'
edition = '2021'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acr = "0.3.2"
chrono = "0.4.38"
crc32fast = "1.4.2"
dh = "0.8.0"
neozip = "0.3.1"
uu_mkdir = "0.0.28"
