# credits: https://github.com/ratatui-org/ratatui/blob/main/.github/workflows/ci.yml
name: Run integration tests
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools
      - name: Install cargo-llvm-cov and cargo-make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-make
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Generate coverage
        run: cargo make coverage
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: ["1.74.0", "stable"]
        backend: [crossterm, termion, termwiz]
        exclude:
          # termion is not supported on windows
          - os: windows-latest
            backend: termion
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust ${{ matrix.toolchain }}}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install cargo-make
        uses: taiki-e/install-action@cargo-make
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Test ${{ matrix.backend }}
        run: cargo make test-backend ${{ matrix.backend }}
        env:
          RUST_BACKTRACE: full